// <auto-generated />
using System;
using Fanoos.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fanoos.Infrastructure.Migrations
{
    [DbContext(typeof(MainDbCtx))]
    [Migration("20260326124805_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("main")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fanoos.Domain.Todos.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Bucket")
                        .HasColumnType("integer")
                        .HasColumnName("bucket");

                    b.Property<string>("Contexts")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contexts");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<int>("EffortType")
                        .HasColumnType("integer")
                        .HasColumnName("effort_type");

                    b.Property<int>("EnergyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("energy_level");

                    b.Property<byte?>("EstimatedPomodoros")
                        .HasColumnType("smallint")
                        .HasColumnName("estimated_pomodoros");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean")
                        .HasColumnName("is_done");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_urgent");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Why")
                        .HasColumnType("text")
                        .HasColumnName("why");

                    b.HasKey("Id")
                        .HasName("pk_todos");

                    b.ToTable("todos", "main");
                });

            modelBuilder.Entity("Fanoos.Domain.Todos.Todo", b =>
                {
                    b.OwnsOne("Fanoos.Domain.Todos.WaitingForInfo", "WaitingForInfo", b1 =>
                        {
                            b1.Property<Guid>("TodoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("waiting_for_description");

                            b1.Property<DateTimeOffset>("ReviewAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("waiting_for_review_at");

                            b1.HasKey("TodoId");

                            b1.ToTable("todos", "main");

                            b1.WithOwner()
                                .HasForeignKey("TodoId")
                                .HasConstraintName("fk_todos_todos_id");
                        });

                    b.Navigation("WaitingForInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
