/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./../../routes/__root"
import { Route as DevRouteImport } from "./../../routes/dev"
import { Route as homeIndexRouteImport } from "./../../routes/(home)/index"
import { Route as AppsTodosNewRouteImport } from "./../../routes/apps/todos/new"
import { Route as AppsTodoshomeIndexRouteImport } from "./../../routes/apps/todos/(home)/index"
import { Route as AppsTodosTodoIdIndexRouteImport } from "./../../routes/apps/todos/$todoId/index"
import { Route as AppsTodosTodoIdEditRouteImport } from "./../../routes/apps/todos/$todoId/edit"

const DevRoute = DevRouteImport.update({
  id: "/dev",
  path: "/dev",
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: "/(home)/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsTodosNewRoute = AppsTodosNewRouteImport.update({
  id: "/apps/todos/new",
  path: "/apps/todos/new",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsTodoshomeIndexRoute = AppsTodoshomeIndexRouteImport.update({
  id: "/apps/todos/(home)/",
  path: "/apps/todos/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsTodosTodoIdIndexRoute = AppsTodosTodoIdIndexRouteImport.update({
  id: "/apps/todos/$todoId/",
  path: "/apps/todos/$todoId/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsTodosTodoIdEditRoute = AppsTodosTodoIdEditRouteImport.update({
  id: "/apps/todos/$todoId/edit",
  path: "/apps/todos/$todoId/edit",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/dev": typeof DevRoute
  "/": typeof homeIndexRoute
  "/apps/todos/new": typeof AppsTodosNewRoute
  "/apps/todos/$todoId/edit": typeof AppsTodosTodoIdEditRoute
  "/apps/todos/$todoId/": typeof AppsTodosTodoIdIndexRoute
  "/apps/todos/": typeof AppsTodoshomeIndexRoute
}
export interface FileRoutesByTo {
  "/dev": typeof DevRoute
  "/": typeof homeIndexRoute
  "/apps/todos/new": typeof AppsTodosNewRoute
  "/apps/todos/$todoId/edit": typeof AppsTodosTodoIdEditRoute
  "/apps/todos/$todoId": typeof AppsTodosTodoIdIndexRoute
  "/apps/todos": typeof AppsTodoshomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/dev": typeof DevRoute
  "/(home)/": typeof homeIndexRoute
  "/apps/todos/new": typeof AppsTodosNewRoute
  "/apps/todos/$todoId/edit": typeof AppsTodosTodoIdEditRoute
  "/apps/todos/$todoId/": typeof AppsTodosTodoIdIndexRoute
  "/apps/todos/(home)/": typeof AppsTodoshomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/dev"
    | "/"
    | "/apps/todos/new"
    | "/apps/todos/$todoId/edit"
    | "/apps/todos/$todoId/"
    | "/apps/todos/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/dev"
    | "/"
    | "/apps/todos/new"
    | "/apps/todos/$todoId/edit"
    | "/apps/todos/$todoId"
    | "/apps/todos"
  id:
    | "__root__"
    | "/dev"
    | "/(home)/"
    | "/apps/todos/new"
    | "/apps/todos/$todoId/edit"
    | "/apps/todos/$todoId/"
    | "/apps/todos/(home)/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DevRoute: typeof DevRoute
  homeIndexRoute: typeof homeIndexRoute
  AppsTodosNewRoute: typeof AppsTodosNewRoute
  AppsTodosTodoIdEditRoute: typeof AppsTodosTodoIdEditRoute
  AppsTodosTodoIdIndexRoute: typeof AppsTodosTodoIdIndexRoute
  AppsTodoshomeIndexRoute: typeof AppsTodoshomeIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/dev": {
      id: "/dev"
      path: "/dev"
      fullPath: "/dev"
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(home)/": {
      id: "/(home)/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/todos/new": {
      id: "/apps/todos/new"
      path: "/apps/todos/new"
      fullPath: "/apps/todos/new"
      preLoaderRoute: typeof AppsTodosNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/todos/(home)/": {
      id: "/apps/todos/(home)/"
      path: "/apps/todos"
      fullPath: "/apps/todos/"
      preLoaderRoute: typeof AppsTodoshomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/todos/$todoId/": {
      id: "/apps/todos/$todoId/"
      path: "/apps/todos/$todoId"
      fullPath: "/apps/todos/$todoId/"
      preLoaderRoute: typeof AppsTodosTodoIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/todos/$todoId/edit": {
      id: "/apps/todos/$todoId/edit"
      path: "/apps/todos/$todoId/edit"
      fullPath: "/apps/todos/$todoId/edit"
      preLoaderRoute: typeof AppsTodosTodoIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DevRoute: DevRoute,
  homeIndexRoute: homeIndexRoute,
  AppsTodosNewRoute: AppsTodosNewRoute,
  AppsTodosTodoIdEditRoute: AppsTodosTodoIdEditRoute,
  AppsTodosTodoIdIndexRoute: AppsTodosTodoIdIndexRoute,
  AppsTodoshomeIndexRoute: AppsTodoshomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
