import type { ContentItemFormat, LocationType } from '#/common/api/client'

export interface FakeContentItem {
  id: string
  title: string
  coverImageUrl: string | null
  placeholderLetter: string
  isFavorited: boolean
  isBookmarked: boolean
  isSecret: boolean
  isOngoing: boolean
  locationType: LocationType | null
  locationValue: string | null
  format: ContentItemFormat
}

export const fakeContentItems: FakeContentItem[] = [
  {
    id: '1',
    title: 'Violet Evergarden',
    coverImageUrl: 'https://animegate.ir/storage/anime/images/2020/10949.webp',
    placeholderLetter: 'V',
    isFavorited: true,
    isBookmarked: false,
    isSecret: false,
    isOngoing: false,
    locationType: 'Url',
    locationValue: 'https://myanimelist.net/anime/33352/Violet_Evergarden',
    format: 'Watchable',
  },
  {
    id: '2',
    title: "Frieren: Beyond Journey's End",
    coverImageUrl: 'https://animegate.ir/storage/anime/images/2023/15852.webp',
    placeholderLetter: 'F',
    isFavorited: true,
    isBookmarked: true,
    isSecret: false,
    isOngoing: true,
    locationType: 'Url',
    locationValue: 'https://myanimelist.net/anime/52991/Sousou_no_Frieren',
    format: 'Watchable',
  },
  {
    id: '3',
    title: 'Atomic Habits',
    coverImageUrl: null,
    placeholderLetter: 'A',
    isFavorited: false,
    isBookmarked: false,
    isSecret: false,
    isOngoing: true,
    locationType: 'Physical',
    locationValue: 'Shelf 2, Row 3',
    format: 'Readable',
  },
  {
    id: '4',
    title: 'Clean Architecture .NET',
    coverImageUrl: null,
    placeholderLetter: 'C',
    isFavorited: false,
    isBookmarked: true,
    isSecret: false,
    isOngoing: true,
    locationType: 'Url',
    locationValue: 'https://dometrain.com/course/clean-architecture-dotnet',
    format: 'Readable',
  },
  {
    id: '5',
    title: 'Horimiya',
    coverImageUrl: 'https://animegate.ir/storage/anime/images/2021/11890.webp',
    placeholderLetter: 'H',
    isFavorited: true,
    isBookmarked: false,
    isSecret: true,
    isOngoing: false,
    locationType: 'Url',
    locationValue: 'https://myanimelist.net/anime/42897/Horimiya',
    format: 'Watchable',
  },
  {
    id: '6',
    title: 'The Lean Startup',
    coverImageUrl: null,
    placeholderLetter: 'L',
    isFavorited: false,
    isBookmarked: false,
    isSecret: false,
    isOngoing: false,
    locationType: null,
    locationValue: null,
    format: 'Readable',
  },
  {
    id: '7',
    title: 'Deep Work',
    coverImageUrl: null,
    placeholderLetter: 'D',
    isFavorited: true,
    isBookmarked: true,
    isSecret: false,
    isOngoing: false,
    locationType: 'Physical',
    locationValue: 'Shelf 1, Row 2',
    format: 'Readable',
  },
  {
    id: '8',
    title: 'JapanesePod101',
    coverImageUrl: null,
    placeholderLetter: 'J',
    isFavorited: false,
    isBookmarked: false,
    isSecret: false,
    isOngoing: true,
    locationType: 'Url',
    locationValue: 'https://japanesepod101.com',
    format: 'Listenable',
  },
  {
    id: '9',
    title: 'Spy x Family',
    coverImageUrl: 'https://animegate.ir/storage/anime/images/2022/13100.webp',
    placeholderLetter: 'S',
    isFavorited: true,
    isBookmarked: true,
    isSecret: false,
    isOngoing: true,
    locationType: 'Url',
    locationValue: 'https://myanimelist.net/anime/50265/Spy_x_Family',
    format: 'Watchable',
  },
  {
    id: '10',
    title: 'Zero to One',
    coverImageUrl: null,
    placeholderLetter: 'Z',
    isFavorited: false,
    isBookmarked: false,
    isSecret: false,
    isOngoing: false,
    locationType: null,
    locationValue: null,
    format: 'Readable',
  },
  {
    id: '11',
    title: 'Figma UI Design Course',
    coverImageUrl: null,
    placeholderLetter: 'F',
    isFavorited: false,
    isBookmarked: true,
    isSecret: false,
    isOngoing: true,
    locationType: 'Url',
    locationValue: 'https://frontendmasters.com/courses/figma',
    format: 'Interactive',
  },
  {
    id: '12',
    title: "Komi Can't Communicate S2",
    coverImageUrl: 'https://animegate.ir/storage/anime/images/2022/12445.webp',
    placeholderLetter: 'K',
    isFavorited: false,
    isBookmarked: false,
    isSecret: true,
    isOngoing: false,
    locationType: 'Url',
    locationValue:
      'https://myanimelist.net/anime/48926/Komi-san_wa_Comyushou_desu_2',
    format: 'Watchable',
  },
  {
    id: '13',
    title: 'Grit',
    coverImageUrl: null,
    placeholderLetter: 'G',
    isFavorited: false,
    isBookmarked: false,
    isSecret: false,
    isOngoing: false,
    locationType: 'Physical',
    locationValue: 'Shelf 3, Row 1',
    format: 'Readable',
  },
  {
    id: '14',
    title: 'Music Theory Podcast',
    coverImageUrl: null,
    placeholderLetter: 'M',
    isFavorited: true,
    isBookmarked: false,
    isSecret: false,
    isOngoing: true,
    locationType: 'Url',
    locationValue: 'https://podcasts.apple.com/us/podcast/music-theory',
    format: 'Listenable',
  },
  {
    id: '15',
    title: 'TypeScript Monorepos',
    coverImageUrl: null,
    placeholderLetter: 'T',
    isFavorited: false,
    isBookmarked: true,
    isSecret: false,
    isOngoing: false,
    locationType: 'Url',
    locationValue: 'https://frontendmasters.com/courses/typescript-monorepos',
    format: 'Interactive',
  },
  {
    id: '16',
    title: 'The Apothecary Diaries',
    coverImageUrl: 'https://animegate.ir/storage/anime/images/2023/15234.webp',
    placeholderLetter: 'A',
    isFavorited: true,
    isBookmarked: false,
    isSecret: false,
    isOngoing: true,
    locationType: 'Url',
    locationValue: 'https://myanimelist.net/anime/54492/Kusuriya_no_Hitorigoto',
    format: 'Watchable',
  },
  {
    id: '17',
    title: 'The E-Myth Revisited',
    coverImageUrl: null,
    placeholderLetter: 'E',
    isFavorited: false,
    isBookmarked: false,
    isSecret: false,
    isOngoing: false,
    locationType: null,
    locationValue: null,
    format: 'Readable',
  },
  {
    id: '18',
    title: 'React Advanced Patterns',
    coverImageUrl: null,
    placeholderLetter: 'R',
    isFavorited: true,
    isBookmarked: true,
    isSecret: false,
    isOngoing: true,
    locationType: 'Url',
    locationValue: 'https://frontendmasters.com/courses/react-patterns',
    format: 'Interactive',
  },
  {
    id: '19',
    title: 'Yuru Camp',
    coverImageUrl: 'https://animegate.ir/storage/anime/images/2018/08349.webp',
    placeholderLetter: 'Y',
    isFavorited: false,
    isBookmarked: true,
    isSecret: true,
    isOngoing: false,
    locationType: 'Url',
    locationValue: 'https://myanimelist.net/anime/34798/Yuru_Camp',
    format: 'Watchable',
  },
  {
    id: '20',
    title: 'Ultralearning',
    coverImageUrl: null,
    placeholderLetter: 'U',
    isFavorited: false,
    isBookmarked: false,
    isSecret: false,
    isOngoing: true,
    locationType: 'Physical',
    locationValue: 'Shelf 2, Row 1',
    format: 'Readable',
  },
]
