# https://taskfile.dev
version: '3'

tasks:
  meta:list:
    aliases: [default, list, l]
    desc: List all tasks
    cmds:
      - task --list-all

  repo:setup:
    aliases: [setup]
    desc: Setup
    cmds:
      - bun install
      - cd web && task setup
      - cd api && task setup

  git:commit:
    aliases: [commit, cm]
    desc: Launch interactive commit
    cmds:
      - bun run cz

  git:commit:all:
    aliases: [commit:all, cma]
    desc: Stage everything and launch interactive commit
    cmds:
      - git add -A
      - bun run cz
