openapi: "3.1.1"
info:
  title: Yorozu.Api | v1
  version: 1.0.0
servers:
  - url: http://localhost:5050/
paths:
  "/api/consumption-track-lists/{id}":
    put:
      tags:
        - Consumption Track Lists
      summary: Update Consumption Track List
      operationId: UpdateConsumptionTrackList
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateConsumptionTrackListRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConsumptionTrackListMiniResponse"
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
    get:
      tags:
        - Consumption Track Lists
      summary: Get Consumption Track List
      operationId: GetConsumptionTrackList
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConsumptionTrackListMiniResponse"
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
    delete:
      tags:
        - Consumption Track Lists
      summary: Delete Consumption Track List
      operationId: DeleteConsumptionTrackList
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
  /api/consumption-track-lists:
    get:
      tags:
        - Consumption Track Lists
      summary: Get Consumption Track Lists
      operationId: ListConsumptionTrackLists
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConsumptionTrackListsResponse"
    post:
      tags:
        - Consumption Track Lists
      summary: Create Consumption Track List
      operationId: CreateConsumptionTrackList
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateConsumptionTrackListRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConsumptionTrackListMiniResponse"
components:
  schemas:
    ConsumptionTrackListMiniResponse:
      required:
        - id
        - createdAt
        - title
        - description
      type: object
      properties:
        id:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
        title:
          type: string
        description:
          type:
            - "null"
            - string
    ConsumptionTrackListsResponse:
      required:
        - items
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/ConsumptionTrackListMiniResponse"
    CreateConsumptionTrackListRequest:
      required:
        - title
      type: object
      properties:
        title:
          type: string
        description:
          type:
            - "null"
            - string
    ProblemDetails:
      type: object
      properties:
        type:
          type:
            - "null"
            - string
        title:
          type:
            - "null"
            - string
        status:
          type:
            - "null"
            - integer
          format: int32
        detail:
          type:
            - "null"
            - string
        instance:
          type:
            - "null"
            - string
    UpdateConsumptionTrackListRequest:
      required:
        - title
        - description
      type: object
      properties:
        title:
          type: string
        description:
          type:
            - "null"
            - string
tags:
  - name: Consumption Track Lists
