openapi: "3.1.1"
info:
  title: Fanoos.Api | v1
  version: 1.0.0
servers:
  - url: http://localhost:5000/
paths:
  /api/todos:
    get:
      tags:
        - Todos
      summary: List todos
      operationId: ListTodos
      parameters:
        - name: bucket
          in: query
          schema:
            $ref: "#/components/schemas/TodoBucketFilter"
        - name: sort_by
          in: query
          schema:
            $ref: "#/components/schemas/TodoSortBy"
        - name: sort_order
          in: query
          schema:
            $ref: "#/components/schemas/TodoSortOrder"
        - name: q
          in: query
          schema:
            type: string
        - name: exclude_query
          in: query
          schema:
            type: string
        - name: available_energy_level
          in: query
          schema:
            $ref: "#/components/schemas/EnergyLevelFilter"
        - name: available_pomodoros
          in: query
          schema:
            type: integer
            format: uint8
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TodoListResponse"
    post:
      tags:
        - Todos
      summary: Create todo
      operationId: CreateTodo
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTodoRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TodoResponse"
  "/api/todos/{id}":
    get:
      tags:
        - Todos
      summary: Get todo
      operationId: GetTodo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TodoResponse"
    delete:
      tags:
        - Todos
      summary: Delete todo
      operationId: DeleteTodo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: No Content
    put:
      tags:
        - Todos
      summary: Change todo
      operationId: ChangeTodo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChangeTodoRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TodoResponse"
  "/api/todos/{id}/completion":
    patch:
      tags:
        - Todos
      summary: Change todo completion
      operationId: ChangeTodoCompletion
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChangeTodoCompletionRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TodoResponse"
  /api/backups:
    get:
      tags:
        - Backups
      summary: Get backup
      operationId: GetBackup
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BackupDto"
    post:
      tags:
        - Backups
      summary: Restore backup
      operationId: RestoreBackup
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BackupDto"
        required: true
      responses:
        "204":
          description: No Content
components:
  schemas:
    BackupDto:
      required:
        - version
        - todos
      type: object
      properties:
        version:
          type: integer
          format: int32
        todos:
          type: array
          items:
            $ref: "#/components/schemas/TodoPersistenceDto"
    ChangeTodoCompletionRequest:
      required:
        - completionChangeAction
      type: object
      properties:
        completionChangeAction:
          $ref: "#/components/schemas/TodoCompletionChangeAction"
    ChangeTodoRequest:
      required:
        - title
        - why
        - description
        - isDone
        - estimatedPomodoros
        - isUrgent
        - dueDate
        - contexts
        - priority
        - effortType
        - energyLevel
        - bucket
        - waitingForInfo
      type: object
      properties:
        title:
          type: string
        why:
          type:
            - "null"
            - string
        description:
          type:
            - "null"
            - string
        isDone:
          type: boolean
        estimatedPomodoros:
          type:
            - "null"
            - integer
          format: uint8
        isUrgent:
          type: boolean
        dueDate:
          type:
            - "null"
            - string
          format: date-time
        contexts:
          type: array
          items:
            type: string
        priority:
          $ref: "#/components/schemas/TodoPriority"
        effortType:
          $ref: "#/components/schemas/TodoEffortType"
        energyLevel:
          $ref: "#/components/schemas/EnergyLevel"
        bucket:
          $ref: "#/components/schemas/TodoBucket"
        waitingForInfo:
          oneOf:
            - type: "null"
            - $ref: "#/components/schemas/WaitingForRequest"
    CreateTodoRequest:
      required:
        - title
      type: object
      properties:
        title:
          type: string
        description:
          type:
            - "null"
            - string
        why:
          type:
            - "null"
            - string
        pomodoroEstimate:
          type:
            - "null"
            - integer
          format: uint8
        isUrgent:
          type:
            - "null"
            - boolean
        isDone:
          type:
            - "null"
            - boolean
        dueDate:
          type:
            - "null"
            - string
          format: date-time
        contexts:
          type:
            - "null"
            - array
          items:
            type: string
        priority:
          oneOf:
            - type: "null"
            - $ref: "#/components/schemas/TodoPriority"
        effortType:
          oneOf:
            - type: "null"
            - $ref: "#/components/schemas/TodoEffortType"
        energyLevel:
          oneOf:
            - type: "null"
            - $ref: "#/components/schemas/EnergyLevel"
        bucket:
          oneOf:
            - type: "null"
            - $ref: "#/components/schemas/TodoBucket"
        waitingForInfo:
          oneOf:
            - type: "null"
            - $ref: "#/components/schemas/WaitingForRequest"
    EnergyLevel:
      enum:
        - Unknown
        - Low
        - Medium
        - High
    EnergyLevelFilter:
      enum:
        - Unknown
        - Low
        - Medium
        - High
        - All
      default: All
    TodoBucket:
      enum:
        - Uncategorized
        - NextActions
        - Waiting
        - SomedayMaybe
    TodoBucketFilter:
      enum:
        - All
        - Uncategorized
        - NextActions
        - Waiting
        - SomedayMaybe
      default: All
    TodoCompletionChangeAction:
      enum:
        - Toggle
        - MarkNotDone
        - MarkDone
    TodoEffortType:
      enum:
        - Unknown
        - Cake
        - Frog
    TodoListResponse:
      required:
        - items
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/TodoResponse"
    TodoPersistenceDto:
      required:
        - id
        - title
        - why
        - description
        - estimatedPomodoros
        - energyLevel
        - bucket
        - isUrgent
        - isDone
        - dueDate
        - contexts
        - priority
        - effortType
        - waitingForInfo
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        why:
          type:
            - "null"
            - string
        description:
          type:
            - "null"
            - string
        estimatedPomodoros:
          type:
            - "null"
            - integer
          format: uint8
        energyLevel:
          type: integer
          format: int32
        bucket:
          type: integer
          format: int32
        isUrgent:
          type: boolean
        isDone:
          type: boolean
        dueDate:
          type:
            - "null"
            - string
          format: date-time
        contexts:
          type: array
          items:
            type: string
        priority:
          type: integer
          format: int32
        effortType:
          type: integer
          format: int32
        waitingForInfo:
          oneOf:
            - type: "null"
            - $ref: "#/components/schemas/WaitingForPersistenceDto"
    TodoPriority:
      enum:
        - Unknown
        - A_MustDo
        - B_ShouldDo
        - C_NiceToDo
        - D_Delegate
        - E_Eliminate
    TodoResponse:
      required:
        - id
        - title
        - why
        - description
        - isDone
        - estimatedPomodoros
        - isUrgent
        - dueDate
        - contexts
        - priority
        - effortType
        - energyLevel
        - bucket
        - waitingForInfo
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        why:
          type:
            - "null"
            - string
        description:
          type:
            - "null"
            - string
        isDone:
          type: boolean
        estimatedPomodoros:
          type:
            - "null"
            - integer
          format: uint8
        isUrgent:
          type: boolean
        dueDate:
          type:
            - "null"
            - string
          format: date-time
        contexts:
          type: array
          items:
            type: string
        priority:
          $ref: "#/components/schemas/TodoPriority"
        effortType:
          $ref: "#/components/schemas/TodoEffortType"
        energyLevel:
          $ref: "#/components/schemas/EnergyLevel"
        bucket:
          $ref: "#/components/schemas/TodoBucket"
        waitingForInfo:
          oneOf:
            - type: "null"
            - $ref: "#/components/schemas/WaitingForResponse"
    TodoSortBy:
      enum:
        - None
        - Title
        - DueDate
        - Priority
      default: None
    TodoSortOrder:
      enum:
        - Asc
        - Desc
      default: Asc
    WaitingForPersistenceDto:
      required:
        - description
        - reviewAt
      type: object
      properties:
        description:
          type: string
        reviewAt:
          type: string
          format: date-time
    WaitingForRequest:
      required:
        - description
        - reviewAt
      type: object
      properties:
        description:
          type: string
        reviewAt:
          type: string
          format: date-time
    WaitingForResponse:
      required:
        - description
        - reviewAt
      type: object
      properties:
        description:
          type: string
        reviewAt:
          type: string
          format: date-time
tags:
  - name: Todos
  - name: Backups
