openapi: '3.1.1'
info:
  title: Fanoos.Api | v1
  version: 1.0.0
servers:
  - url: http://localhost:5000/
paths:
  '/api/todos/{id}':
    patch:
      tags:
        - Todos
      summary: Change todo
      operationId: ChangeTodo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeTodoRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoResponse'
  /api/todos:
    post:
      tags:
        - Todos
      summary: Create todo
      operationId: CreateTodo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTodoRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoResponse'
    get:
      tags:
        - Todos
      summary: List todos
      operationId: ListTodos
      parameters:
        - name: include_archived
          in: query
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoListResponse'
components:
  schemas:
    ChangeTodoRequest:
      type: object
      properties:
        rawTitle:
          oneOf:
            - type: 'null'
            - $ref: '#/components/schemas/ValueStringObject'
        isDone:
          oneOf:
            - type: 'null'
            - $ref: '#/components/schemas/ValueBooleanObject'
        isArchived:
          oneOf:
            - type: 'null'
            - $ref: '#/components/schemas/ValueBooleanObject'
    CreateTodoRequest:
      required:
        - rawTitle
      type: object
      properties:
        rawTitle:
          type: string
    TodoListResponse:
      required:
        - items
        - includesArchived
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/TodoResponse'
        includesArchived:
          type: boolean
    TodoResponse:
      required:
        - id
        - title
        - rawTitle
        - context
        - project
        - time
        - tag
        - energy
        - isImportant
        - isUrgent
        - isDone
        - isArchived
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        rawTitle:
          type: string
        context:
          type:
            - 'null'
            - string
        project:
          type:
            - 'null'
            - string
        time:
          pattern: '^-?(?:0|[1-9]\d*)$'
          type:
            - 'null'
            - integer
            - string
          format: int32
        tag:
          type:
            - 'null'
            - string
        energy:
          type:
            - 'null'
            - string
        isImportant:
          type: boolean
        isUrgent:
          type: boolean
        isDone:
          type: boolean
        isArchived:
          type: boolean
    ValueBooleanObject:
      required:
        - value
      type: object
      properties:
        value:
          type: boolean
    ValueStringObject:
      required:
        - value
      type: object
      properties:
        value:
          type: string
tags:
  - name: Todos