import {
  BooksIcon,
  FileAudioIcon,
  KanbanIcon,
  ListChecksIcon,
  BookmarkIcon,
  ClipboardIcon,
  UserIcon,
  CalendarCheckIcon,
  CardsIcon,
  SmileyIcon,
  MusicNotesIcon,
  NotebookIcon,
  ChatIcon,
  PencilIcon,
  TimerIcon,
  CubeFocusIcon,
} from "@phosphor-icons/react"
import type { IAppShortcut } from "./-IAppShortcut"
import { linkOptions } from "@tanstack/react-router"

export const appShortcuts: IAppShortcut[] = [
  {
    id: "hondana",
    name: "本棚",
    icon: BooksIcon,
    url: linkOptions({ to: "/apps/hondana" }).to,
    type: "APP",
  },
  {
    id: "time-log",
    name: "Time Log",
    icon: TimerIcon,
    url: linkOptions({ to: "/apps/time-log" }).to,
    type: "APP",
  },
  {
    id: "spotlight",
    name: "Spotlight",
    icon: CubeFocusIcon,
    url: linkOptions({ to: "/apps/spotlight" }).to,
    type: "APP",
  },

  {
    id: "choice",
    name: "Choice",
    icon: ListChecksIcon,
    url: linkOptions({ to: "/apps/choice" }).to,
    type: "MVP",
  },
  {
    id: "kanban",
    name: "Kanban",
    icon: KanbanIcon,
    url: linkOptions({ to: "/apps/kanban" }).to,
    type: "MVP",
  },
  {
    id: "lyrics",
    name: "Lyrics",
    icon: FileAudioIcon,
    url: linkOptions({ to: "/apps/lyrics" }).to,
    type: "MVP",
  },

  {
    id: "bookmarks",
    name: "Bookmarks",
    icon: BookmarkIcon,
    type: "IDEA",
    description: "Organise bookmarks by project, topic, or category.",
  },
  {
    id: "checklists",
    name: "Checklists",
    icon: ClipboardIcon,
    type: "IDEA",
    description: "Create reusable checklists with steps, substeps, and states.",
  },
  {
    id: "contacts",
    name: "Contacts",
    icon: UserIcon,
    type: "IDEA",
    description: "Manage contacts with rich fields and relationship tags.",
  },
  {
    id: "habits",
    name: "Habit Tracker",
    icon: CalendarCheckIcon,
    type: "IDEA",
    description: "Track daily habits with streaks and heatmap view.",
  },
  {
    id: "kanji",
    name: "Kanji Cards",
    icon: CardsIcon,
    type: "IDEA",
    description: "Physical knowledge cards with digital companion app.",
  },
  {
    id: "mood",
    name: "Mood Tracker",
    icon: SmileyIcon,
    type: "IDEA",
    description: "Log moods, context, and discover patterns over time.",
  },
  {
    id: "music",
    name: "Music Library",
    icon: MusicNotesIcon,
    type: "IDEA",
    description: "Categorised music library with moods, genres, and lyrics.",
  },
  {
    id: "notes",
    name: "Notes",
    icon: NotebookIcon,
    type: "IDEA",
    description: "Virtual bookshelf of notebooks with rich content.",
  },
  {
    id: "prompts",
    name: "Prompt Manager",
    icon: ChatIcon,
    type: "IDEA",
    description: "Categorised library of dynamic prompts with variables.",
  },
  {
    id: "writing",
    name: "Writing Area",
    icon: PencilIcon,
    type: "IDEA",
    description: "Distraction-free writing with themes and font customisation.",
  },
]
