/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./../../routes/__root"
import { Route as DevRouteImport } from "./../../routes/dev"
import { Route as homeIndexRouteImport } from "./../../routes/(home)/index"
import { Route as AppsWritingAreaRouteImport } from "./../../routes/apps/writing-area"
import { Route as AppsVoiceNotesRouteImport } from "./../../routes/apps/voice-notes"
import { Route as AppsVideoPlayerRouteImport } from "./../../routes/apps/video-player"
import { Route as AppsTtsRouteImport } from "./../../routes/apps/tts"
import { Route as AppsTimeLogRouteImport } from "./../../routes/apps/time-log"
import { Route as AppsSpotlightRouteImport } from "./../../routes/apps/spotlight"
import { Route as AppsQrReaderRouteImport } from "./../../routes/apps/qr-reader"
import { Route as AppsQrGeneratorRouteImport } from "./../../routes/apps/qr-generator"
import { Route as AppsPasswordGeneratorRouteImport } from "./../../routes/apps/password-generator"
import { Route as AppsKanbanRouteImport } from "./../../routes/apps/kanban"
import { Route as AppsChoiceRouteImport } from "./../../routes/apps/choice"
import { Route as AppsShirabeIndexRouteImport } from "./../../routes/apps/shirabe/index"
import { Route as AppsHondanaIndexRouteImport } from "./../../routes/apps/hondana/index"
import { Route as AppshomeIndexRouteImport } from "./../../routes/apps/(home)/index"
import { Route as AppsShirabeEditorRouteImport } from "./../../routes/apps/shirabe/editor"
import { Route as AppsHondanaSettingsRouteImport } from "./../../routes/apps/hondana/settings"
import { Route as AppsHondanaTracksIndexRouteImport } from "./../../routes/apps/hondana/tracks.index"
import { Route as AppsHondanaLibraryIndexRouteImport } from "./../../routes/apps/hondana/library.index"
import { Route as AppsHondanaLibraryNewRouteImport } from "./../../routes/apps/hondana/library.new"
import { Route as AppsHondanaTracksIdIndexRouteImport } from "./../../routes/apps/hondana/tracks.$id.index"
import { Route as AppsHondanaLibraryIdIndexRouteImport } from "./../../routes/apps/hondana/library.$id.index"
import { Route as AppsHondanaTracksIdEditRouteImport } from "./../../routes/apps/hondana/tracks.$id.edit"
import { Route as AppsHondanaLibraryIdEditRouteImport } from "./../../routes/apps/hondana/library.$id.edit"
import { Route as AppsHondanaLibraryIdTracksNewRouteImport } from "./../../routes/apps/hondana/library.$id.tracks.new"

const DevRoute = DevRouteImport.update({
  id: "/dev",
  path: "/dev",
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: "/(home)/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsWritingAreaRoute = AppsWritingAreaRouteImport.update({
  id: "/apps/writing-area",
  path: "/apps/writing-area",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsVoiceNotesRoute = AppsVoiceNotesRouteImport.update({
  id: "/apps/voice-notes",
  path: "/apps/voice-notes",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsVideoPlayerRoute = AppsVideoPlayerRouteImport.update({
  id: "/apps/video-player",
  path: "/apps/video-player",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsTtsRoute = AppsTtsRouteImport.update({
  id: "/apps/tts",
  path: "/apps/tts",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsTimeLogRoute = AppsTimeLogRouteImport.update({
  id: "/apps/time-log",
  path: "/apps/time-log",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsSpotlightRoute = AppsSpotlightRouteImport.update({
  id: "/apps/spotlight",
  path: "/apps/spotlight",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsQrReaderRoute = AppsQrReaderRouteImport.update({
  id: "/apps/qr-reader",
  path: "/apps/qr-reader",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsQrGeneratorRoute = AppsQrGeneratorRouteImport.update({
  id: "/apps/qr-generator",
  path: "/apps/qr-generator",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsPasswordGeneratorRoute = AppsPasswordGeneratorRouteImport.update({
  id: "/apps/password-generator",
  path: "/apps/password-generator",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsKanbanRoute = AppsKanbanRouteImport.update({
  id: "/apps/kanban",
  path: "/apps/kanban",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsChoiceRoute = AppsChoiceRouteImport.update({
  id: "/apps/choice",
  path: "/apps/choice",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsShirabeIndexRoute = AppsShirabeIndexRouteImport.update({
  id: "/apps/shirabe/",
  path: "/apps/shirabe/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsHondanaIndexRoute = AppsHondanaIndexRouteImport.update({
  id: "/apps/hondana/",
  path: "/apps/hondana/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppshomeIndexRoute = AppshomeIndexRouteImport.update({
  id: "/apps/(home)/",
  path: "/apps/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsShirabeEditorRoute = AppsShirabeEditorRouteImport.update({
  id: "/apps/shirabe/editor",
  path: "/apps/shirabe/editor",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsHondanaSettingsRoute = AppsHondanaSettingsRouteImport.update({
  id: "/apps/hondana/settings",
  path: "/apps/hondana/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsHondanaTracksIndexRoute = AppsHondanaTracksIndexRouteImport.update({
  id: "/apps/hondana/tracks/",
  path: "/apps/hondana/tracks/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsHondanaLibraryIndexRoute = AppsHondanaLibraryIndexRouteImport.update({
  id: "/apps/hondana/library/",
  path: "/apps/hondana/library/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsHondanaLibraryNewRoute = AppsHondanaLibraryNewRouteImport.update({
  id: "/apps/hondana/library/new",
  path: "/apps/hondana/library/new",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsHondanaTracksIdIndexRoute =
  AppsHondanaTracksIdIndexRouteImport.update({
    id: "/apps/hondana/tracks/$id/",
    path: "/apps/hondana/tracks/$id/",
    getParentRoute: () => rootRouteImport,
  } as any)
const AppsHondanaLibraryIdIndexRoute =
  AppsHondanaLibraryIdIndexRouteImport.update({
    id: "/apps/hondana/library/$id/",
    path: "/apps/hondana/library/$id/",
    getParentRoute: () => rootRouteImport,
  } as any)
const AppsHondanaTracksIdEditRoute = AppsHondanaTracksIdEditRouteImport.update({
  id: "/apps/hondana/tracks/$id/edit",
  path: "/apps/hondana/tracks/$id/edit",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsHondanaLibraryIdEditRoute =
  AppsHondanaLibraryIdEditRouteImport.update({
    id: "/apps/hondana/library/$id/edit",
    path: "/apps/hondana/library/$id/edit",
    getParentRoute: () => rootRouteImport,
  } as any)
const AppsHondanaLibraryIdTracksNewRoute =
  AppsHondanaLibraryIdTracksNewRouteImport.update({
    id: "/apps/hondana/library/$id/tracks/new",
    path: "/apps/hondana/library/$id/tracks/new",
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  "/dev": typeof DevRoute
  "/apps/choice": typeof AppsChoiceRoute
  "/apps/kanban": typeof AppsKanbanRoute
  "/apps/password-generator": typeof AppsPasswordGeneratorRoute
  "/apps/qr-generator": typeof AppsQrGeneratorRoute
  "/apps/qr-reader": typeof AppsQrReaderRoute
  "/apps/spotlight": typeof AppsSpotlightRoute
  "/apps/time-log": typeof AppsTimeLogRoute
  "/apps/tts": typeof AppsTtsRoute
  "/apps/video-player": typeof AppsVideoPlayerRoute
  "/apps/voice-notes": typeof AppsVoiceNotesRoute
  "/apps/writing-area": typeof AppsWritingAreaRoute
  "/": typeof homeIndexRoute
  "/apps/hondana/settings": typeof AppsHondanaSettingsRoute
  "/apps/shirabe/editor": typeof AppsShirabeEditorRoute
  "/apps/": typeof AppshomeIndexRoute
  "/apps/hondana/": typeof AppsHondanaIndexRoute
  "/apps/shirabe/": typeof AppsShirabeIndexRoute
  "/apps/hondana/library/new": typeof AppsHondanaLibraryNewRoute
  "/apps/hondana/library/": typeof AppsHondanaLibraryIndexRoute
  "/apps/hondana/tracks/": typeof AppsHondanaTracksIndexRoute
  "/apps/hondana/library/$id/edit": typeof AppsHondanaLibraryIdEditRoute
  "/apps/hondana/tracks/$id/edit": typeof AppsHondanaTracksIdEditRoute
  "/apps/hondana/library/$id/": typeof AppsHondanaLibraryIdIndexRoute
  "/apps/hondana/tracks/$id/": typeof AppsHondanaTracksIdIndexRoute
  "/apps/hondana/library/$id/tracks/new": typeof AppsHondanaLibraryIdTracksNewRoute
}
export interface FileRoutesByTo {
  "/dev": typeof DevRoute
  "/apps/choice": typeof AppsChoiceRoute
  "/apps/kanban": typeof AppsKanbanRoute
  "/apps/password-generator": typeof AppsPasswordGeneratorRoute
  "/apps/qr-generator": typeof AppsQrGeneratorRoute
  "/apps/qr-reader": typeof AppsQrReaderRoute
  "/apps/spotlight": typeof AppsSpotlightRoute
  "/apps/time-log": typeof AppsTimeLogRoute
  "/apps/tts": typeof AppsTtsRoute
  "/apps/video-player": typeof AppsVideoPlayerRoute
  "/apps/voice-notes": typeof AppsVoiceNotesRoute
  "/apps/writing-area": typeof AppsWritingAreaRoute
  "/": typeof homeIndexRoute
  "/apps/hondana/settings": typeof AppsHondanaSettingsRoute
  "/apps/shirabe/editor": typeof AppsShirabeEditorRoute
  "/apps": typeof AppshomeIndexRoute
  "/apps/hondana": typeof AppsHondanaIndexRoute
  "/apps/shirabe": typeof AppsShirabeIndexRoute
  "/apps/hondana/library/new": typeof AppsHondanaLibraryNewRoute
  "/apps/hondana/library": typeof AppsHondanaLibraryIndexRoute
  "/apps/hondana/tracks": typeof AppsHondanaTracksIndexRoute
  "/apps/hondana/library/$id/edit": typeof AppsHondanaLibraryIdEditRoute
  "/apps/hondana/tracks/$id/edit": typeof AppsHondanaTracksIdEditRoute
  "/apps/hondana/library/$id": typeof AppsHondanaLibraryIdIndexRoute
  "/apps/hondana/tracks/$id": typeof AppsHondanaTracksIdIndexRoute
  "/apps/hondana/library/$id/tracks/new": typeof AppsHondanaLibraryIdTracksNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/dev": typeof DevRoute
  "/apps/choice": typeof AppsChoiceRoute
  "/apps/kanban": typeof AppsKanbanRoute
  "/apps/password-generator": typeof AppsPasswordGeneratorRoute
  "/apps/qr-generator": typeof AppsQrGeneratorRoute
  "/apps/qr-reader": typeof AppsQrReaderRoute
  "/apps/spotlight": typeof AppsSpotlightRoute
  "/apps/time-log": typeof AppsTimeLogRoute
  "/apps/tts": typeof AppsTtsRoute
  "/apps/video-player": typeof AppsVideoPlayerRoute
  "/apps/voice-notes": typeof AppsVoiceNotesRoute
  "/apps/writing-area": typeof AppsWritingAreaRoute
  "/(home)/": typeof homeIndexRoute
  "/apps/hondana/settings": typeof AppsHondanaSettingsRoute
  "/apps/shirabe/editor": typeof AppsShirabeEditorRoute
  "/apps/(home)/": typeof AppshomeIndexRoute
  "/apps/hondana/": typeof AppsHondanaIndexRoute
  "/apps/shirabe/": typeof AppsShirabeIndexRoute
  "/apps/hondana/library/new": typeof AppsHondanaLibraryNewRoute
  "/apps/hondana/library/": typeof AppsHondanaLibraryIndexRoute
  "/apps/hondana/tracks/": typeof AppsHondanaTracksIndexRoute
  "/apps/hondana/library/$id/edit": typeof AppsHondanaLibraryIdEditRoute
  "/apps/hondana/tracks/$id/edit": typeof AppsHondanaTracksIdEditRoute
  "/apps/hondana/library/$id/": typeof AppsHondanaLibraryIdIndexRoute
  "/apps/hondana/tracks/$id/": typeof AppsHondanaTracksIdIndexRoute
  "/apps/hondana/library/$id/tracks/new": typeof AppsHondanaLibraryIdTracksNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/dev"
    | "/apps/choice"
    | "/apps/kanban"
    | "/apps/password-generator"
    | "/apps/qr-generator"
    | "/apps/qr-reader"
    | "/apps/spotlight"
    | "/apps/time-log"
    | "/apps/tts"
    | "/apps/video-player"
    | "/apps/voice-notes"
    | "/apps/writing-area"
    | "/"
    | "/apps/hondana/settings"
    | "/apps/shirabe/editor"
    | "/apps/"
    | "/apps/hondana/"
    | "/apps/shirabe/"
    | "/apps/hondana/library/new"
    | "/apps/hondana/library/"
    | "/apps/hondana/tracks/"
    | "/apps/hondana/library/$id/edit"
    | "/apps/hondana/tracks/$id/edit"
    | "/apps/hondana/library/$id/"
    | "/apps/hondana/tracks/$id/"
    | "/apps/hondana/library/$id/tracks/new"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/dev"
    | "/apps/choice"
    | "/apps/kanban"
    | "/apps/password-generator"
    | "/apps/qr-generator"
    | "/apps/qr-reader"
    | "/apps/spotlight"
    | "/apps/time-log"
    | "/apps/tts"
    | "/apps/video-player"
    | "/apps/voice-notes"
    | "/apps/writing-area"
    | "/"
    | "/apps/hondana/settings"
    | "/apps/shirabe/editor"
    | "/apps"
    | "/apps/hondana"
    | "/apps/shirabe"
    | "/apps/hondana/library/new"
    | "/apps/hondana/library"
    | "/apps/hondana/tracks"
    | "/apps/hondana/library/$id/edit"
    | "/apps/hondana/tracks/$id/edit"
    | "/apps/hondana/library/$id"
    | "/apps/hondana/tracks/$id"
    | "/apps/hondana/library/$id/tracks/new"
  id:
    | "__root__"
    | "/dev"
    | "/apps/choice"
    | "/apps/kanban"
    | "/apps/password-generator"
    | "/apps/qr-generator"
    | "/apps/qr-reader"
    | "/apps/spotlight"
    | "/apps/time-log"
    | "/apps/tts"
    | "/apps/video-player"
    | "/apps/voice-notes"
    | "/apps/writing-area"
    | "/(home)/"
    | "/apps/hondana/settings"
    | "/apps/shirabe/editor"
    | "/apps/(home)/"
    | "/apps/hondana/"
    | "/apps/shirabe/"
    | "/apps/hondana/library/new"
    | "/apps/hondana/library/"
    | "/apps/hondana/tracks/"
    | "/apps/hondana/library/$id/edit"
    | "/apps/hondana/tracks/$id/edit"
    | "/apps/hondana/library/$id/"
    | "/apps/hondana/tracks/$id/"
    | "/apps/hondana/library/$id/tracks/new"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DevRoute: typeof DevRoute
  AppsChoiceRoute: typeof AppsChoiceRoute
  AppsKanbanRoute: typeof AppsKanbanRoute
  AppsPasswordGeneratorRoute: typeof AppsPasswordGeneratorRoute
  AppsQrGeneratorRoute: typeof AppsQrGeneratorRoute
  AppsQrReaderRoute: typeof AppsQrReaderRoute
  AppsSpotlightRoute: typeof AppsSpotlightRoute
  AppsTimeLogRoute: typeof AppsTimeLogRoute
  AppsTtsRoute: typeof AppsTtsRoute
  AppsVideoPlayerRoute: typeof AppsVideoPlayerRoute
  AppsVoiceNotesRoute: typeof AppsVoiceNotesRoute
  AppsWritingAreaRoute: typeof AppsWritingAreaRoute
  homeIndexRoute: typeof homeIndexRoute
  AppsHondanaSettingsRoute: typeof AppsHondanaSettingsRoute
  AppsShirabeEditorRoute: typeof AppsShirabeEditorRoute
  AppshomeIndexRoute: typeof AppshomeIndexRoute
  AppsHondanaIndexRoute: typeof AppsHondanaIndexRoute
  AppsShirabeIndexRoute: typeof AppsShirabeIndexRoute
  AppsHondanaLibraryNewRoute: typeof AppsHondanaLibraryNewRoute
  AppsHondanaLibraryIndexRoute: typeof AppsHondanaLibraryIndexRoute
  AppsHondanaTracksIndexRoute: typeof AppsHondanaTracksIndexRoute
  AppsHondanaLibraryIdEditRoute: typeof AppsHondanaLibraryIdEditRoute
  AppsHondanaTracksIdEditRoute: typeof AppsHondanaTracksIdEditRoute
  AppsHondanaLibraryIdIndexRoute: typeof AppsHondanaLibraryIdIndexRoute
  AppsHondanaTracksIdIndexRoute: typeof AppsHondanaTracksIdIndexRoute
  AppsHondanaLibraryIdTracksNewRoute: typeof AppsHondanaLibraryIdTracksNewRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/dev": {
      id: "/dev"
      path: "/dev"
      fullPath: "/dev"
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(home)/": {
      id: "/(home)/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/writing-area": {
      id: "/apps/writing-area"
      path: "/apps/writing-area"
      fullPath: "/apps/writing-area"
      preLoaderRoute: typeof AppsWritingAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/voice-notes": {
      id: "/apps/voice-notes"
      path: "/apps/voice-notes"
      fullPath: "/apps/voice-notes"
      preLoaderRoute: typeof AppsVoiceNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/video-player": {
      id: "/apps/video-player"
      path: "/apps/video-player"
      fullPath: "/apps/video-player"
      preLoaderRoute: typeof AppsVideoPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/tts": {
      id: "/apps/tts"
      path: "/apps/tts"
      fullPath: "/apps/tts"
      preLoaderRoute: typeof AppsTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/time-log": {
      id: "/apps/time-log"
      path: "/apps/time-log"
      fullPath: "/apps/time-log"
      preLoaderRoute: typeof AppsTimeLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/spotlight": {
      id: "/apps/spotlight"
      path: "/apps/spotlight"
      fullPath: "/apps/spotlight"
      preLoaderRoute: typeof AppsSpotlightRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/qr-reader": {
      id: "/apps/qr-reader"
      path: "/apps/qr-reader"
      fullPath: "/apps/qr-reader"
      preLoaderRoute: typeof AppsQrReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/qr-generator": {
      id: "/apps/qr-generator"
      path: "/apps/qr-generator"
      fullPath: "/apps/qr-generator"
      preLoaderRoute: typeof AppsQrGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/password-generator": {
      id: "/apps/password-generator"
      path: "/apps/password-generator"
      fullPath: "/apps/password-generator"
      preLoaderRoute: typeof AppsPasswordGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/kanban": {
      id: "/apps/kanban"
      path: "/apps/kanban"
      fullPath: "/apps/kanban"
      preLoaderRoute: typeof AppsKanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/choice": {
      id: "/apps/choice"
      path: "/apps/choice"
      fullPath: "/apps/choice"
      preLoaderRoute: typeof AppsChoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/shirabe/": {
      id: "/apps/shirabe/"
      path: "/apps/shirabe"
      fullPath: "/apps/shirabe/"
      preLoaderRoute: typeof AppsShirabeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/hondana/": {
      id: "/apps/hondana/"
      path: "/apps/hondana"
      fullPath: "/apps/hondana/"
      preLoaderRoute: typeof AppsHondanaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/(home)/": {
      id: "/apps/(home)/"
      path: "/apps"
      fullPath: "/apps/"
      preLoaderRoute: typeof AppshomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/shirabe/editor": {
      id: "/apps/shirabe/editor"
      path: "/apps/shirabe/editor"
      fullPath: "/apps/shirabe/editor"
      preLoaderRoute: typeof AppsShirabeEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/hondana/settings": {
      id: "/apps/hondana/settings"
      path: "/apps/hondana/settings"
      fullPath: "/apps/hondana/settings"
      preLoaderRoute: typeof AppsHondanaSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/hondana/tracks/": {
      id: "/apps/hondana/tracks/"
      path: "/apps/hondana/tracks"
      fullPath: "/apps/hondana/tracks/"
      preLoaderRoute: typeof AppsHondanaTracksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/hondana/library/": {
      id: "/apps/hondana/library/"
      path: "/apps/hondana/library"
      fullPath: "/apps/hondana/library/"
      preLoaderRoute: typeof AppsHondanaLibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/hondana/library/new": {
      id: "/apps/hondana/library/new"
      path: "/apps/hondana/library/new"
      fullPath: "/apps/hondana/library/new"
      preLoaderRoute: typeof AppsHondanaLibraryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/hondana/tracks/$id/": {
      id: "/apps/hondana/tracks/$id/"
      path: "/apps/hondana/tracks/$id"
      fullPath: "/apps/hondana/tracks/$id/"
      preLoaderRoute: typeof AppsHondanaTracksIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/hondana/library/$id/": {
      id: "/apps/hondana/library/$id/"
      path: "/apps/hondana/library/$id"
      fullPath: "/apps/hondana/library/$id/"
      preLoaderRoute: typeof AppsHondanaLibraryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/hondana/tracks/$id/edit": {
      id: "/apps/hondana/tracks/$id/edit"
      path: "/apps/hondana/tracks/$id/edit"
      fullPath: "/apps/hondana/tracks/$id/edit"
      preLoaderRoute: typeof AppsHondanaTracksIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/hondana/library/$id/edit": {
      id: "/apps/hondana/library/$id/edit"
      path: "/apps/hondana/library/$id/edit"
      fullPath: "/apps/hondana/library/$id/edit"
      preLoaderRoute: typeof AppsHondanaLibraryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/hondana/library/$id/tracks/new": {
      id: "/apps/hondana/library/$id/tracks/new"
      path: "/apps/hondana/library/$id/tracks/new"
      fullPath: "/apps/hondana/library/$id/tracks/new"
      preLoaderRoute: typeof AppsHondanaLibraryIdTracksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DevRoute: DevRoute,
  AppsChoiceRoute: AppsChoiceRoute,
  AppsKanbanRoute: AppsKanbanRoute,
  AppsPasswordGeneratorRoute: AppsPasswordGeneratorRoute,
  AppsQrGeneratorRoute: AppsQrGeneratorRoute,
  AppsQrReaderRoute: AppsQrReaderRoute,
  AppsSpotlightRoute: AppsSpotlightRoute,
  AppsTimeLogRoute: AppsTimeLogRoute,
  AppsTtsRoute: AppsTtsRoute,
  AppsVideoPlayerRoute: AppsVideoPlayerRoute,
  AppsVoiceNotesRoute: AppsVoiceNotesRoute,
  AppsWritingAreaRoute: AppsWritingAreaRoute,
  homeIndexRoute: homeIndexRoute,
  AppsHondanaSettingsRoute: AppsHondanaSettingsRoute,
  AppsShirabeEditorRoute: AppsShirabeEditorRoute,
  AppshomeIndexRoute: AppshomeIndexRoute,
  AppsHondanaIndexRoute: AppsHondanaIndexRoute,
  AppsShirabeIndexRoute: AppsShirabeIndexRoute,
  AppsHondanaLibraryNewRoute: AppsHondanaLibraryNewRoute,
  AppsHondanaLibraryIndexRoute: AppsHondanaLibraryIndexRoute,
  AppsHondanaTracksIndexRoute: AppsHondanaTracksIndexRoute,
  AppsHondanaLibraryIdEditRoute: AppsHondanaLibraryIdEditRoute,
  AppsHondanaTracksIdEditRoute: AppsHondanaTracksIdEditRoute,
  AppsHondanaLibraryIdIndexRoute: AppsHondanaLibraryIdIndexRoute,
  AppsHondanaTracksIdIndexRoute: AppsHondanaTracksIdIndexRoute,
  AppsHondanaLibraryIdTracksNewRoute: AppsHondanaLibraryIdTracksNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
