/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./../../routes/__root"
import { Route as DevRouteImport } from "./../../routes/dev"
import { Route as homeIndexRouteImport } from "./../../routes/(home)/index"
import { Route as AppsSingleFocusRouteImport } from "./../../routes/apps/single-focus"
import { Route as AppsKanbanRouteImport } from "./../../routes/apps/kanban"
import { Route as AppsChronoTrackRouteImport } from "./../../routes/apps/chrono-track"
import { Route as AppsChoiceRouteImport } from "./../../routes/apps/choice"
import { Route as AppsLyricsIndexRouteImport } from "./../../routes/apps/lyrics/index"
import { Route as AppsHondanaIndexRouteImport } from "./../../routes/apps/hondana/index"
import { Route as AppshomeIndexRouteImport } from "./../../routes/apps/(home)/index"
import { Route as AppsLyricsIdRouteImport } from "./../../routes/apps/lyrics/$id"
import { Route as AppsHondanaSettingsRouteImport } from "./../../routes/apps/hondana/settings"
import { Route as AppsHondanaCliRouteImport } from "./../../routes/apps/hondana/cli"
import { Route as AppsHondanaTracksIndexRouteImport } from "./../../routes/apps/hondana/tracks.index"
import { Route as AppsHondanaLibraryIndexRouteImport } from "./../../routes/apps/hondana/library.index"
import { Route as AppsLyricsPrintIdRouteImport } from "./../../routes/apps/lyrics/print.$id"
import { Route as AppsHondanaLibraryNewRouteImport } from "./../../routes/apps/hondana/library.new"
import { Route as AppsHondanaLibraryIdIndexRouteImport } from "./../../routes/apps/hondana/library.$id.index"
import { Route as AppsHondanaLibraryIdEditRouteImport } from "./../../routes/apps/hondana/library.$id.edit"
import { Route as AppsHondanaLibraryIdTracksNewRouteImport } from "./../../routes/apps/hondana/library.$id.tracks.new"

const DevRoute = DevRouteImport.update({
  id: "/dev",
  path: "/dev",
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: "/(home)/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsSingleFocusRoute = AppsSingleFocusRouteImport.update({
  id: "/apps/single-focus",
  path: "/apps/single-focus",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsKanbanRoute = AppsKanbanRouteImport.update({
  id: "/apps/kanban",
  path: "/apps/kanban",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsChronoTrackRoute = AppsChronoTrackRouteImport.update({
  id: "/apps/chrono-track",
  path: "/apps/chrono-track",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsChoiceRoute = AppsChoiceRouteImport.update({
  id: "/apps/choice",
  path: "/apps/choice",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsLyricsIndexRoute = AppsLyricsIndexRouteImport.update({
  id: "/apps/lyrics/",
  path: "/apps/lyrics/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsHondanaIndexRoute = AppsHondanaIndexRouteImport.update({
  id: "/apps/hondana/",
  path: "/apps/hondana/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppshomeIndexRoute = AppshomeIndexRouteImport.update({
  id: "/apps/(home)/",
  path: "/apps/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsLyricsIdRoute = AppsLyricsIdRouteImport.update({
  id: "/apps/lyrics/$id",
  path: "/apps/lyrics/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsHondanaSettingsRoute = AppsHondanaSettingsRouteImport.update({
  id: "/apps/hondana/settings",
  path: "/apps/hondana/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsHondanaCliRoute = AppsHondanaCliRouteImport.update({
  id: "/apps/hondana/cli",
  path: "/apps/hondana/cli",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsHondanaTracksIndexRoute = AppsHondanaTracksIndexRouteImport.update({
  id: "/apps/hondana/tracks/",
  path: "/apps/hondana/tracks/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsHondanaLibraryIndexRoute = AppsHondanaLibraryIndexRouteImport.update({
  id: "/apps/hondana/library/",
  path: "/apps/hondana/library/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsLyricsPrintIdRoute = AppsLyricsPrintIdRouteImport.update({
  id: "/apps/lyrics/print/$id",
  path: "/apps/lyrics/print/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsHondanaLibraryNewRoute = AppsHondanaLibraryNewRouteImport.update({
  id: "/apps/hondana/library/new",
  path: "/apps/hondana/library/new",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsHondanaLibraryIdIndexRoute =
  AppsHondanaLibraryIdIndexRouteImport.update({
    id: "/apps/hondana/library/$id/",
    path: "/apps/hondana/library/$id/",
    getParentRoute: () => rootRouteImport,
  } as any)
const AppsHondanaLibraryIdEditRoute =
  AppsHondanaLibraryIdEditRouteImport.update({
    id: "/apps/hondana/library/$id/edit",
    path: "/apps/hondana/library/$id/edit",
    getParentRoute: () => rootRouteImport,
  } as any)
const AppsHondanaLibraryIdTracksNewRoute =
  AppsHondanaLibraryIdTracksNewRouteImport.update({
    id: "/apps/hondana/library/$id/tracks/new",
    path: "/apps/hondana/library/$id/tracks/new",
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  "/dev": typeof DevRoute
  "/apps/choice": typeof AppsChoiceRoute
  "/apps/chrono-track": typeof AppsChronoTrackRoute
  "/apps/kanban": typeof AppsKanbanRoute
  "/apps/single-focus": typeof AppsSingleFocusRoute
  "/": typeof homeIndexRoute
  "/apps/hondana/cli": typeof AppsHondanaCliRoute
  "/apps/hondana/settings": typeof AppsHondanaSettingsRoute
  "/apps/lyrics/$id": typeof AppsLyricsIdRoute
  "/apps/": typeof AppshomeIndexRoute
  "/apps/hondana/": typeof AppsHondanaIndexRoute
  "/apps/lyrics/": typeof AppsLyricsIndexRoute
  "/apps/hondana/library/new": typeof AppsHondanaLibraryNewRoute
  "/apps/lyrics/print/$id": typeof AppsLyricsPrintIdRoute
  "/apps/hondana/library/": typeof AppsHondanaLibraryIndexRoute
  "/apps/hondana/tracks/": typeof AppsHondanaTracksIndexRoute
  "/apps/hondana/library/$id/edit": typeof AppsHondanaLibraryIdEditRoute
  "/apps/hondana/library/$id/": typeof AppsHondanaLibraryIdIndexRoute
  "/apps/hondana/library/$id/tracks/new": typeof AppsHondanaLibraryIdTracksNewRoute
}
export interface FileRoutesByTo {
  "/dev": typeof DevRoute
  "/apps/choice": typeof AppsChoiceRoute
  "/apps/chrono-track": typeof AppsChronoTrackRoute
  "/apps/kanban": typeof AppsKanbanRoute
  "/apps/single-focus": typeof AppsSingleFocusRoute
  "/": typeof homeIndexRoute
  "/apps/hondana/cli": typeof AppsHondanaCliRoute
  "/apps/hondana/settings": typeof AppsHondanaSettingsRoute
  "/apps/lyrics/$id": typeof AppsLyricsIdRoute
  "/apps": typeof AppshomeIndexRoute
  "/apps/hondana": typeof AppsHondanaIndexRoute
  "/apps/lyrics": typeof AppsLyricsIndexRoute
  "/apps/hondana/library/new": typeof AppsHondanaLibraryNewRoute
  "/apps/lyrics/print/$id": typeof AppsLyricsPrintIdRoute
  "/apps/hondana/library": typeof AppsHondanaLibraryIndexRoute
  "/apps/hondana/tracks": typeof AppsHondanaTracksIndexRoute
  "/apps/hondana/library/$id/edit": typeof AppsHondanaLibraryIdEditRoute
  "/apps/hondana/library/$id": typeof AppsHondanaLibraryIdIndexRoute
  "/apps/hondana/library/$id/tracks/new": typeof AppsHondanaLibraryIdTracksNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/dev": typeof DevRoute
  "/apps/choice": typeof AppsChoiceRoute
  "/apps/chrono-track": typeof AppsChronoTrackRoute
  "/apps/kanban": typeof AppsKanbanRoute
  "/apps/single-focus": typeof AppsSingleFocusRoute
  "/(home)/": typeof homeIndexRoute
  "/apps/hondana/cli": typeof AppsHondanaCliRoute
  "/apps/hondana/settings": typeof AppsHondanaSettingsRoute
  "/apps/lyrics/$id": typeof AppsLyricsIdRoute
  "/apps/(home)/": typeof AppshomeIndexRoute
  "/apps/hondana/": typeof AppsHondanaIndexRoute
  "/apps/lyrics/": typeof AppsLyricsIndexRoute
  "/apps/hondana/library/new": typeof AppsHondanaLibraryNewRoute
  "/apps/lyrics/print/$id": typeof AppsLyricsPrintIdRoute
  "/apps/hondana/library/": typeof AppsHondanaLibraryIndexRoute
  "/apps/hondana/tracks/": typeof AppsHondanaTracksIndexRoute
  "/apps/hondana/library/$id/edit": typeof AppsHondanaLibraryIdEditRoute
  "/apps/hondana/library/$id/": typeof AppsHondanaLibraryIdIndexRoute
  "/apps/hondana/library/$id/tracks/new": typeof AppsHondanaLibraryIdTracksNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/dev"
    | "/apps/choice"
    | "/apps/chrono-track"
    | "/apps/kanban"
    | "/apps/single-focus"
    | "/"
    | "/apps/hondana/cli"
    | "/apps/hondana/settings"
    | "/apps/lyrics/$id"
    | "/apps/"
    | "/apps/hondana/"
    | "/apps/lyrics/"
    | "/apps/hondana/library/new"
    | "/apps/lyrics/print/$id"
    | "/apps/hondana/library/"
    | "/apps/hondana/tracks/"
    | "/apps/hondana/library/$id/edit"
    | "/apps/hondana/library/$id/"
    | "/apps/hondana/library/$id/tracks/new"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/dev"
    | "/apps/choice"
    | "/apps/chrono-track"
    | "/apps/kanban"
    | "/apps/single-focus"
    | "/"
    | "/apps/hondana/cli"
    | "/apps/hondana/settings"
    | "/apps/lyrics/$id"
    | "/apps"
    | "/apps/hondana"
    | "/apps/lyrics"
    | "/apps/hondana/library/new"
    | "/apps/lyrics/print/$id"
    | "/apps/hondana/library"
    | "/apps/hondana/tracks"
    | "/apps/hondana/library/$id/edit"
    | "/apps/hondana/library/$id"
    | "/apps/hondana/library/$id/tracks/new"
  id:
    | "__root__"
    | "/dev"
    | "/apps/choice"
    | "/apps/chrono-track"
    | "/apps/kanban"
    | "/apps/single-focus"
    | "/(home)/"
    | "/apps/hondana/cli"
    | "/apps/hondana/settings"
    | "/apps/lyrics/$id"
    | "/apps/(home)/"
    | "/apps/hondana/"
    | "/apps/lyrics/"
    | "/apps/hondana/library/new"
    | "/apps/lyrics/print/$id"
    | "/apps/hondana/library/"
    | "/apps/hondana/tracks/"
    | "/apps/hondana/library/$id/edit"
    | "/apps/hondana/library/$id/"
    | "/apps/hondana/library/$id/tracks/new"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DevRoute: typeof DevRoute
  AppsChoiceRoute: typeof AppsChoiceRoute
  AppsChronoTrackRoute: typeof AppsChronoTrackRoute
  AppsKanbanRoute: typeof AppsKanbanRoute
  AppsSingleFocusRoute: typeof AppsSingleFocusRoute
  homeIndexRoute: typeof homeIndexRoute
  AppsHondanaCliRoute: typeof AppsHondanaCliRoute
  AppsHondanaSettingsRoute: typeof AppsHondanaSettingsRoute
  AppsLyricsIdRoute: typeof AppsLyricsIdRoute
  AppshomeIndexRoute: typeof AppshomeIndexRoute
  AppsHondanaIndexRoute: typeof AppsHondanaIndexRoute
  AppsLyricsIndexRoute: typeof AppsLyricsIndexRoute
  AppsHondanaLibraryNewRoute: typeof AppsHondanaLibraryNewRoute
  AppsLyricsPrintIdRoute: typeof AppsLyricsPrintIdRoute
  AppsHondanaLibraryIndexRoute: typeof AppsHondanaLibraryIndexRoute
  AppsHondanaTracksIndexRoute: typeof AppsHondanaTracksIndexRoute
  AppsHondanaLibraryIdEditRoute: typeof AppsHondanaLibraryIdEditRoute
  AppsHondanaLibraryIdIndexRoute: typeof AppsHondanaLibraryIdIndexRoute
  AppsHondanaLibraryIdTracksNewRoute: typeof AppsHondanaLibraryIdTracksNewRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/dev": {
      id: "/dev"
      path: "/dev"
      fullPath: "/dev"
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(home)/": {
      id: "/(home)/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/single-focus": {
      id: "/apps/single-focus"
      path: "/apps/single-focus"
      fullPath: "/apps/single-focus"
      preLoaderRoute: typeof AppsSingleFocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/kanban": {
      id: "/apps/kanban"
      path: "/apps/kanban"
      fullPath: "/apps/kanban"
      preLoaderRoute: typeof AppsKanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/chrono-track": {
      id: "/apps/chrono-track"
      path: "/apps/chrono-track"
      fullPath: "/apps/chrono-track"
      preLoaderRoute: typeof AppsChronoTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/choice": {
      id: "/apps/choice"
      path: "/apps/choice"
      fullPath: "/apps/choice"
      preLoaderRoute: typeof AppsChoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/lyrics/": {
      id: "/apps/lyrics/"
      path: "/apps/lyrics"
      fullPath: "/apps/lyrics/"
      preLoaderRoute: typeof AppsLyricsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/hondana/": {
      id: "/apps/hondana/"
      path: "/apps/hondana"
      fullPath: "/apps/hondana/"
      preLoaderRoute: typeof AppsHondanaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/(home)/": {
      id: "/apps/(home)/"
      path: "/apps"
      fullPath: "/apps/"
      preLoaderRoute: typeof AppshomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/lyrics/$id": {
      id: "/apps/lyrics/$id"
      path: "/apps/lyrics/$id"
      fullPath: "/apps/lyrics/$id"
      preLoaderRoute: typeof AppsLyricsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/hondana/settings": {
      id: "/apps/hondana/settings"
      path: "/apps/hondana/settings"
      fullPath: "/apps/hondana/settings"
      preLoaderRoute: typeof AppsHondanaSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/hondana/cli": {
      id: "/apps/hondana/cli"
      path: "/apps/hondana/cli"
      fullPath: "/apps/hondana/cli"
      preLoaderRoute: typeof AppsHondanaCliRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/hondana/tracks/": {
      id: "/apps/hondana/tracks/"
      path: "/apps/hondana/tracks"
      fullPath: "/apps/hondana/tracks/"
      preLoaderRoute: typeof AppsHondanaTracksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/hondana/library/": {
      id: "/apps/hondana/library/"
      path: "/apps/hondana/library"
      fullPath: "/apps/hondana/library/"
      preLoaderRoute: typeof AppsHondanaLibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/lyrics/print/$id": {
      id: "/apps/lyrics/print/$id"
      path: "/apps/lyrics/print/$id"
      fullPath: "/apps/lyrics/print/$id"
      preLoaderRoute: typeof AppsLyricsPrintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/hondana/library/new": {
      id: "/apps/hondana/library/new"
      path: "/apps/hondana/library/new"
      fullPath: "/apps/hondana/library/new"
      preLoaderRoute: typeof AppsHondanaLibraryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/hondana/library/$id/": {
      id: "/apps/hondana/library/$id/"
      path: "/apps/hondana/library/$id"
      fullPath: "/apps/hondana/library/$id/"
      preLoaderRoute: typeof AppsHondanaLibraryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/hondana/library/$id/edit": {
      id: "/apps/hondana/library/$id/edit"
      path: "/apps/hondana/library/$id/edit"
      fullPath: "/apps/hondana/library/$id/edit"
      preLoaderRoute: typeof AppsHondanaLibraryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/hondana/library/$id/tracks/new": {
      id: "/apps/hondana/library/$id/tracks/new"
      path: "/apps/hondana/library/$id/tracks/new"
      fullPath: "/apps/hondana/library/$id/tracks/new"
      preLoaderRoute: typeof AppsHondanaLibraryIdTracksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DevRoute: DevRoute,
  AppsChoiceRoute: AppsChoiceRoute,
  AppsChronoTrackRoute: AppsChronoTrackRoute,
  AppsKanbanRoute: AppsKanbanRoute,
  AppsSingleFocusRoute: AppsSingleFocusRoute,
  homeIndexRoute: homeIndexRoute,
  AppsHondanaCliRoute: AppsHondanaCliRoute,
  AppsHondanaSettingsRoute: AppsHondanaSettingsRoute,
  AppsLyricsIdRoute: AppsLyricsIdRoute,
  AppshomeIndexRoute: AppshomeIndexRoute,
  AppsHondanaIndexRoute: AppsHondanaIndexRoute,
  AppsLyricsIndexRoute: AppsLyricsIndexRoute,
  AppsHondanaLibraryNewRoute: AppsHondanaLibraryNewRoute,
  AppsLyricsPrintIdRoute: AppsLyricsPrintIdRoute,
  AppsHondanaLibraryIndexRoute: AppsHondanaLibraryIndexRoute,
  AppsHondanaTracksIndexRoute: AppsHondanaTracksIndexRoute,
  AppsHondanaLibraryIdEditRoute: AppsHondanaLibraryIdEditRoute,
  AppsHondanaLibraryIdIndexRoute: AppsHondanaLibraryIdIndexRoute,
  AppsHondanaLibraryIdTracksNewRoute: AppsHondanaLibraryIdTracksNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
