import type { LyricSong } from "../LyricSong"

export const killShot: LyricSong = {
  id: "kill-shot",
  title: "Kill Shot",
  artist: "RIIZE",
  animeTitle: "Kill Blue",
  animeUrl: "https://animegate.ir/anime/kill-ao-21440",
  defaultPrimaryLanguage: "ja",
  lines: [
    { en: "Kill shot" },
    { en: "Kill shot" },
    { en: "Kill shot" },
    { en: "Kill shot" },
    { en: "Pull the, pull the trigger" },
    {
      ja: "Ah, まとまんない",
      romaji: "Ah, matomannai",
      en: "Ah, I can’t get it together",
    },
    {
      ja: "<ruby>待<rt>ま</rt></ruby>って、まとまんない",
      romaji: "Matte, matomannai",
      en: "Wait, I can’t get it together",
    },
    {
      ja: "<ruby>当<rt>あ</rt></ruby>たり<ruby>前<rt>まえ</rt></ruby>じゃん",
      romaji: "Atarimae jan",
      en: "Of course, right?",
    },
    {
      ja: "それ、<ruby>当<rt>あ</rt></ruby>たり<ruby>前<rt>まえ</rt></ruby>じゃん",
      romaji: "Sore, atarimae jan",
      en: "That’s obvious, right?",
    },
    {
      ja: "<ruby>明日<rt>あした</rt></ruby>から<ruby>中学生<rt>ちゅうがくせい</rt></ruby>",
      romaji: "Ashita kara chuugakusei",
      en: "Starting middle school tomorrow",
    },
    {
      ja: "<ruby>頭<rt>あたま</rt></ruby>ん<ruby>中<rt>なか</rt></ruby>パンクしてる",
      romaji: "Atama nnaka panku shiteru",
      en: "My head’s about to burst",
    },
    { en: "No, it cannot be true" },
    {
      ja: "バグった<ruby>将来<rt>しょうらい</rt></ruby>のビジョン",
      romaji: "Bagutta shourai no bijon",
      en: "A glitched-out vision of the future",
    },
    { en: "Oh no, oh no, oh no" },
    {
      ja: "<ruby>明日<rt>あした</rt></ruby>から Restart",
      romaji: "Asu kara Restart",
      en: "Starting tomorrow—restart",
    },
    { en: "Ride, ride or die" },
    {
      ja: "<ruby>提出<rt>ていしゅつ</rt></ruby>コンテンツ　<ruby>要<rt>よう</rt></ruby>チェック",
      romaji: "Teishutsu kontentsu you chekku",
      en: "Submitted content—check it",
    },
    { en: "Tick tock tick tock" },
    {
      ja: "<ruby>前<rt>まえ</rt></ruby> <ruby>前<rt>まえ</rt></ruby>ならえ",
      romaji: "Mae mae narae",
      en: "Line up, follow the lead",
    },
    {
      ja: "Yah　ついていくしかないじゃん",
      romaji: "Yah tsuite iku shika nai jan",
      en: "Yeah, I’ve got no choice but to keep up",
    },
    {
      ja: "グルチャのテンポ",
      romaji: "Gurucha no tenpo",
      en: "With the group chat’s tempo",
    },
    {
      ja: "<ruby>欠<rt>か</rt></ruby>けていた<ruby>情熱<rt>じょうねつ</rt></ruby>",
      romaji: "Kaketeita jounetsu",
      en: "The passion I lacked",
    },
    {
      ja: "<ruby>上<rt>あ</rt></ruby>がってくモチベ",
      romaji: "Agatteku mochibe",
      en: "My motivation rising",
    },
    { en: "Don’t stop, pop, pop" },
    { en: "We’re going up, up, up higher" },
    {
      ja: "<ruby>暗闇<rt>くらやみ</rt></ruby>の<ruby>中<rt>なか</rt></ruby>",
      romaji: "Kurayami no naka",
      en: "In the darkness",
    },
    {
      ja: "<ruby>無音<rt>むおん</rt></ruby>で drive",
      romaji: "Muon de drive",
      en: "Driving in silence",
    },
    {
      ja: "<ruby>孤独<rt>こどく</rt></ruby>な<ruby>傷跡<rt>きずあと</rt></ruby>が",
      romaji: "Kodoku na kizuato ga",
      en: "Lonely scars",
    },
    {
      ja: "<ruby>名前<rt>なまえ</rt></ruby>を<ruby>呼<rt>よ</rt></ruby>ぶ<ruby>声<rt>こえ</rt></ruby>に<ruby>今<rt>いま</rt></ruby>",
      romaji: "Namae wo yobu koe ni ima",
      en: "Are now filled and healed",
    },
    {
      ja: "<ruby>満<rt>み</rt></ruby>たされ<ruby>癒<rt>い</rt></ruby>えていく",
      romaji: "Mitasare iete iku",
      en: "By a voice calling my name",
    },
    {
      ja: "<ruby>始<rt>はじ</rt></ruby>まったんだ",
      romaji: "Hajimattan da",
      en: "It’s begun",
    },
    {
      ja: "<ruby>駆<rt>か</rt></ruby>け<ruby>出<rt>だ</rt></ruby>す<ruby>未来<rt>みらい</rt></ruby>は<ruby>今<rt>いま</rt></ruby>",
      romaji: "Kakedasu mirai wa ima",
      en: "The future takes off now",
    },
    {
      ja: "<ruby>狙<rt>ねら</rt></ruby>い<ruby>定<rt>さだ</rt></ruby>めた",
      romaji: "Neraisadameta",
      en: "I’ve locked onto my target",
    },
    { en: "Because I’m a winner" },
    {
      ja: "<ruby>迷<rt>まよ</rt></ruby>うたびに<ruby>笑<rt>わら</rt></ruby>い<ruby>飛<rt>と</rt></ruby>ばしていけ",
      romaji: "Mayou tabi ni waraitobashite ike",
      en: "Whenever I hesitate, I’ll just laugh it off",
    },
    {
      ja: "<ruby>外<rt>はず</rt></ruby>さない<ruby>弾道<rt>だんどう</rt></ruby>",
      romaji: "Hazusanai dandou",
      en: "A trajectory that never misses",
    },
    { en: "Because I’m a winner" },
    {
      ja: "この<ruby>弾丸<rt>たま</rt></ruby>は fire fire",
      romaji: "Kono tama wa fire fire",
      en: "This bullet is fire, fire",
    },
    {
      ja: "Breaking the chains　<ruby>夢<rt>ゆめ</rt></ruby>はもう",
      romaji: "Breaking the chains yume wa mou",
      en: "Breaking the chains—my dream",
    },
    {
      ja: "Never ever　<ruby>捨<rt>す</rt></ruby>てない promise",
      romaji: "Never ever sutenai promise",
      en: "Never ever—I won’t throw away this promise",
    },
    { en: "I will never give up, give up" },
    { en: "Give up, give up" },
    { en: "I’m on a rampage" },
    { en: "Here comes my kill shot" },
    {
      ja: "サイレント killin’",
      romaji: "Sairento killin’",
      en: "Silent killin’",
    },
    {
      ja: "Lemme　<ruby>上<rt>うえ</rt></ruby>に gotta get it",
      romaji: "Lemme ue ni gotta get it",
      en: "Lemme—aim higher, gotta get it",
    },
    {
      ja: "100% lock in　<ruby>口<rt>くち</rt></ruby>だけ<ruby>無理<rt>むり</rt></ruby> wow",
      romaji: "Hundred percent lock in kuchi dake muri wow",
      en: "100% locked in—just talk won’t cut it, wow",
    },
    {
      ja: "<ruby>狙<rt>ねら</rt></ruby>いを<ruby>定<rt>さだ</rt></ruby>めろ lock on",
      romaji: "Nerai wo sadamero lock on",
      en: "Take aim—lock on",
    },
    {
      ja: "<ruby>俺<rt>おれ</rt></ruby>の<ruby>視界<rt>しかい</rt></ruby>　<ruby>広<rt>ひろ</rt></ruby>すぎもう",
      romaji: "Ore no shikai hirosugi mou",
      en: "My field of view’s already too wide",
    },
    {
      ja: "‘ありのまま’が KEY",
      romaji: "“Ari no mama” ga KEY",
      en: "“Being myself” is the key",
    },
    {
      ja: "<ruby>拾<rt>ひろ</rt></ruby>い<ruby>集<rt>あつ</rt></ruby>めるピース",
      romaji: "Hiroiatsumeru piisu",
      en: "Gathering up the pieces",
    },
    {
      ja: "まるで Duke <ruby>東郷<rt>とうごう</rt></ruby>　スナイパー",
      romaji: "Marude Duke Tougou sunaipaa",
      en: "Like Duke Togo, a sniper",
    },
    {
      ja: "<ruby>静寂<rt>せいじゃく</rt></ruby>のトリガー",
      romaji: "Seijaku no torigaa",
      en: "A silent trigger",
    },
    {
      ja: "<ruby>暗闇<rt>くらやみ</rt></ruby>の<ruby>中<rt>なか</rt></ruby>",
      romaji: "Kurayami no naka",
      en: "In the darkness",
    },
    {
      ja: "<ruby>無音<rt>むおん</rt></ruby>で drive",
      romaji: "Muon de drive",
      en: "Driving in silence",
    },
    {
      ja: "<ruby>孤独<rt>こどく</rt></ruby>な<ruby>傷跡<rt>きずあと</rt></ruby>が",
      romaji: "Kodoku na kizuato ga",
      en: "Lonely scars",
    },
    {
      ja: "<ruby>名前<rt>なまえ</rt></ruby>を<ruby>呼<rt>よ</rt></ruby>ぶ<ruby>声<rt>こえ</rt></ruby>に<ruby>今<rt>いま</rt></ruby>",
      romaji: "Namae wo yobu koe ni ima",
      en: "Are now filled and healed",
    },
    {
      ja: "<ruby>満<rt>み</rt></ruby>たされ<ruby>癒<rt>い</rt></ruby>えていく",
      romaji: "Mitasare iete iku",
      en: "By a voice calling my name",
    },
    {
      ja: "<ruby>始<rt>はじ</rt></ruby>まったんだ",
      romaji: "Hajimattan da",
      en: "It’s begun",
    },
    {
      ja: "<ruby>駆<rt>か</rt></ruby>け<ruby>出<rt>だ</rt></ruby>す<ruby>未来<rt>みらい</rt></ruby>は<ruby>今<rt>いま</rt></ruby>",
      romaji: "Kakedasu mirai wa ima",
      en: "The future takes off now",
    },
    {
      ja: "<ruby>狙<rt>ねら</rt></ruby>い<ruby>定<rt>さだ</rt></ruby>めた",
      romaji: "Neraisadameta",
      en: "I’ve locked onto my target",
    },
    { en: "Because I’m a winner" },
    {
      ja: "<ruby>迷<rt>まよ</rt></ruby>うたびに<ruby>笑<rt>わら</rt></ruby>い<ruby>飛<rt>と</rt></ruby>ばしていけ",
      romaji: "Mayou tabi ni waraitobashite ike",
      en: "Whenever I hesitate, I’ll just laugh it off",
    },
    {
      ja: "<ruby>外<rt>はず</rt></ruby>さない<ruby>弾道<rt>だんどう</rt></ruby>",
      romaji: "Hazusanai dandou",
      en: "A trajectory that never misses",
    },
    { en: "Because I’m a winner" },
    {
      ja: "この<ruby>弾丸<rt>たま</rt></ruby>は fire fire",
      romaji: "Kono tama wa fire fire",
      en: "This bullet is fire, fire",
    },
    {
      ja: "Breaking the chains　<ruby>夢<rt>ゆめ</rt></ruby>はもう",
      romaji: "Breaking the chains yume wa mou",
      en: "Breaking the chains—my dream",
    },
    {
      ja: "Never ever　<ruby>捨<rt>す</rt></ruby>てない promise",
      romaji: "Never ever sutenai promise",
      en: "Never ever—I won’t throw away this promise",
    },
    { en: "I will never give up, give up" },
    { en: "Give up, give up" },
    { en: "I’m on a rampage" },
    { en: "Here comes my kill shot" },
    {
      ja: "<ruby>教室<rt>きょうしつ</rt></ruby>の<ruby>温<rt>ぬく</rt></ruby>もりが",
      romaji: "Kyoushitsu no nukumori ga",
      en: "The warmth of the classroom",
    },
    {
      ja: "<ruby>錆<rt>さ</rt></ruby>びていた<ruby>心<rt>こころ</rt></ruby>",
      romaji: "Sabiteita kokoro",
      en: "Untangles",
    },
    {
      ja: "<ruby>解<rt>ほど</rt></ruby>いていくそうさ",
      romaji: "Hodoite iku sou sa",
      en: "My rusted heart",
    },
    {
      ja: "<ruby>探<rt>さが</rt></ruby>していた Answer",
      romaji: "Sagashiteita Answer",
      en: "The answer I’d been searching for",
    },
    {
      ja: "ここに<ruby>見<rt>み</rt></ruby>つけられたから",
      romaji: "Koko ni mitsukerareta kara",
      en: "I found it here",
    },
    {
      ja: "<ruby>始<rt>はじ</rt></ruby>まったんだ",
      romaji: "Hajimattan da",
      en: "It’s begun",
    },
    {
      ja: "<ruby>駆<rt>か</rt></ruby>け<ruby>出<rt>だ</rt></ruby>す<ruby>未来<rt>みらい</rt></ruby>は<ruby>今<rt>いま</rt></ruby>",
      romaji: "Kakedasu mirai wa ima",
      en: "The future takes off now",
    },
    {
      ja: "<ruby>狙<rt>ねら</rt></ruby>い<ruby>定<rt>さだ</rt></ruby>めた",
      romaji: "Neraisadameta",
      en: "I’ve locked onto my target",
    },
    { en: "Because I’m a winner" },
    {
      ja: "<ruby>迷<rt>まよ</rt></ruby>うたびに<ruby>笑<rt>わら</rt></ruby>い<ruby>飛<rt>と</rt></ruby>ばしていけ",
      romaji: "Mayou tabi ni waraitobashite ike",
      en: "Whenever I hesitate, I’ll just laugh it off",
    },
    {
      ja: "<ruby>外<rt>はず</rt></ruby>さない<ruby>弾道<rt>だんどう</rt></ruby>",
      romaji: "Hazusanai dandou",
      en: "A trajectory that never misses",
    },
    { en: "Because I’m a winner" },
    {
      ja: "この<ruby>弾丸<rt>たま</rt></ruby>は fire fire",
      romaji: "Kono tama wa fire fire",
      en: "This bullet is fire, fire",
    },
    {
      ja: "Breaking the chains　<ruby>夢<rt>ゆめ</rt></ruby>はもう",
      romaji: "Breaking the chains yume wa mou",
      en: "Breaking the chains—my dream",
    },
    {
      ja: "Never ever　<ruby>捨<rt>す</rt></ruby>てない promise",
      romaji: "Never ever sutenai promise",
      en: "Never ever—I won’t throw away this promise",
    },
    { en: "I will never give up, give up" },
    { en: "Give up, give up" },
    { en: "I’m on a rampage" },
    { en: "Here comes my kill shot" },
  ],
}
