// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yorozu.Infrastructure.Database;

#nullable disable

namespace Yorozu.Infrastructure.Migrations
{
    [DbContext(typeof(MainDbCtx))]
    [Migration("20260616122123_RemoveGenres")]
    partial class RemoveGenres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Yorozu.Domain.ContentItems.ConsumptionTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentUnit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DroppedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PausedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentItemId");

                    b.ToTable("ConsumptionTrack");
                });

            modelBuilder.Entity("Yorozu.Domain.ContentItems.ContentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Format")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBookmarked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NickName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceholderColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("_tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContentItems");
                });

            modelBuilder.Entity("Yorozu.Domain.ContentItems.ConsumptionTrack", b =>
                {
                    b.HasOne("Yorozu.Domain.ContentItems.ContentItem", null)
                        .WithMany("ConsumptionTracks")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Yorozu.Domain.ContentItems.ContentItem", b =>
                {
                    b.OwnsOne("Yorozu.Domain.ContentItems.ContentUnitSpec", "UnitSpec", b1 =>
                        {
                            b1.Property<Guid>("ContentItemId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsOngoing")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("TotalUnits")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("UnitType")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ContentItemId");

                            b1.ToTable("ContentItems");

                            b1.WithOwner()
                                .HasForeignKey("ContentItemId");
                        });

                    b.OwnsOne("Yorozu.Domain.ContentItems.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("ContentItemId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ContentItemId");

                            b1.ToTable("ContentItems");

                            b1.WithOwner()
                                .HasForeignKey("ContentItemId");
                        });

                    b.Navigation("Location");

                    b.Navigation("UnitSpec");
                });

            modelBuilder.Entity("Yorozu.Domain.ContentItems.ContentItem", b =>
                {
                    b.Navigation("ConsumptionTracks");
                });
#pragma warning restore 612, 618
        }
    }
}
