// <auto-generated />
using System;
using Yorozu.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Yorozu.Infrastructure.Migrations
{
    [DbContext(typeof(MainDbCtx))]
    partial class MainDbCtxModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("main")
                .HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Yorozu.Domain.Todos.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("Bucket")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bucket");

                    b.Property<string>("Contexts")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("contexts");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("due_date");

                    b.Property<int>("EffortType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("effort_type");

                    b.Property<int>("EnergyLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("energy_level");

                    b.Property<byte?>("EstimatedPomodoros")
                        .HasColumnType("INTEGER")
                        .HasColumnName("estimated_pomodoros");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_done");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_urgent");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("Why")
                        .HasColumnType("TEXT")
                        .HasColumnName("why");

                    b.HasKey("Id")
                        .HasName("pk_todos");

                    b.ToTable("todos", "main");
                });

            modelBuilder.Entity("Yorozu.Domain.Todos.Todo", b =>
                {
                    b.OwnsOne("Yorozu.Domain.Todos.WaitingForInfo", "WaitingForInfo", b1 =>
                        {
                            b1.Property<Guid>("TodoId")
                                .HasColumnType("TEXT")
                                .HasColumnName("id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("waiting_for_description");

                            b1.Property<DateTimeOffset>("ReviewAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("waiting_for_review_at");

                            b1.HasKey("TodoId");

                            b1.ToTable("todos", "main");

                            b1.WithOwner()
                                .HasForeignKey("TodoId")
                                .HasConstraintName("fk_todos_todos_id");
                        });

                    b.Navigation("WaitingForInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
