# https://taskfile.dev
version: "3"

tasks:
  # ---- meta ----
  meta:list:
    aliases: [default]
    desc: List all tasks
    cmds:
      - task --list-all

  # ---- app ----
  app:dev:
    aliases: [dev, d]
    desc: Start Vite dev server
    cmds:
      - npm run vite -- --host

  app:preview:
    desc: Preview production build
    cmds:
      - npm run vite -- preview --host

  app:build:only:
    desc: Build project without type checking
    cmds:
      - npm run vite -- build

  app:build:full:
    aliases: [publish]
    desc: Type-check then build project
    cmds:
      - task: quality:type-check
      - task: app:build:only

  # ---- api ----
  api:def:
    aliases: [acgd]
    desc: Download OpenAPI definition
    cmds:
      - curl -o "./src/common/api/openapi.yaml" "http://localhost:5000/openapi.yaml"

  api:gen:
    aliases: [acg]
    desc: Generate API client
    cmds:
      - npm run openapi-ts

  api:all:
    desc: Refresh API client (definition + generate)
    cmds:
      - task: api:def
      - task: api:gen

  # ---- quality ----
  quality:type-check:
    aliases: [t]
    desc: Run TypeScript type checking
    cmds:
      - npm run tsc -- -b

  quality:format:
    aliases: [f]
    desc: Run Prettier to format code
    cmds:
      - npm run prettier -- . --write

  # ---- test ----
  test:unit:
    desc: Run unit tests with Vitest
    cmds:
      - npm run vitest
